/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_alexandroskarargyris_myapplication_NativeClass */

#ifndef _Included_com_example_alexandroskarargyris_myapplication_NativeClass
#define _Included_com_example_alexandroskarargyris_myapplication_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_alexandroskarargyris_myapplication_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alexandroskarargyris_myapplication_NativeClass_getStringFromNative
        (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
